### ISSUE TITLE
pls add my pull requests

### ISSUE THREAD

**Issue by ktprime** [JacksonAllan/c_cpp_hash_tables_benchmark#3]
can u merge my pull request, I have add my new hash map emilib2 which is also very fast.

**Comment by JacksonAllan** [comment]
Hi @ktprime, sorry for the very slow response!

As you saw, I’ve merged the pull request and made some adjustments to bring it in line with recent changes to the benchmarks. [Here](https://profound-macaron-930a14.netlify.app/) are the results I get for 20,000,000 keys with emhash7 and emilib2o included. Looks really good!

A few points:

1. Would you like me to include the library in my [article](https://jacksonallan.github.io/c_cpp_hash_tables_benchmark/) accompanying the benchmarks? If so, I will probably only include emilib2o because the article is getting very crowded, and emilib2o seems to match or outperform emhash7 under most circumstances.
2. emilib2o is not respecting the 0.875 maximum load factor, which is an issue for these benchmarks. Although the function `max_load_factor` implies that 0.875 (i.e. 7/8) is the hard-coded default, the function `reserve` (which seems to control when the table grows) seems to use a load factor of 0.83 (i.e. `num_elems + num_elems / 5`). To make emilib2o respect the 0.875 maximum, in `reserve` I replaced the line ` size_t required_buckets = num_elems + num_elems / 5; ` with ` size_t required_buckets = num_elems / max_load_factor(); `.
3. emilib2o doesn’t appear to have been released for public consumption yet. I can only find it buried in “thirdparty” [here](https://github.com/ktprime/emhash/blob/master/thirdparty/emilib/emilib2o.hpp), and that file isn’t quite the same as the one you included in the pull request. If you’d like me to include it in the article, then what’s its current status? Is it still a work in progress, and will it be released soon? How should I refer to it?
4. My article includes a description of each hash table benchmarked. If you’d like me to include emilib2o, then can you provide some details about its implementation? It seems to be a SIMD-accelerated linear probing table using tombstones. So how does it differ from absl::flat_hash_map (i.e. Swiss tables) and/or boost::unordered_flat_map?

**Comment by ktprime** [comment]
The emilib2 library in my repository has been under development for over 3 years. It follows the same principles as the Swiss hash table and incorporates optimizations for efficient insertion and erasure operations. It offers several different versions with varying features.

  One notable distinction from the absl library is that emilib2 utilizes one byte of each entry to track the distance from the home bucket to the fastest bucket. This design choice enhances its performance. Additionally, the codebase of emilib2 is easier to read compared to Boost and absl, although there may be differences in code style and API design.

Please note that the above description has been revised based on the information provided. Feel free to make further adjustments or additions as needed.

**Comment by ktprime** [comment]
btw, I test your code on different hardware and system with different compilers, hash function, such as apple m2, amd 5800h, intel server cpu, it's result quite different from pc cpu(high speed but less cpu cache)

**Comment by JacksonAllan** [comment]
Thanks for the quick response! A few more comments/queries:

1. I’ve replaced the version of emilib2o that you supplied in the PR request with the file found [here](https://github.com/ktprime/emhash/blob/434a20571a8d6b83b308ee0655a7076b5177e1fc/thirdparty/emilib/emilib2o.hpp) (`434a205`) so that I have something to refer readers to.

2. When I compile emilib2o.hpp without first including hash_table7.hpp, I get the following error:
    ```
    In file included from shims/emilib2O/shim.h:11,
                     from main.cpp:311:
    shims/emilib2O/emilib2o_modified.hpp: In function 'uint32_t emilib2::CTZ(uint64_t)':
    shims/emilib2O/emilib2o_modified.hpp:101:9: error: '_BitScanForward64' was not declared in this scope
      101 |         _BitScanForward64(&index, n);
    ```
    To make the error disappear, I have to add
    ```
    #if _WIN32
    #include <intrin.h>
    #endif
    ```
   before including the header. I’m using [GCC 13.2.0 under MinGW](https://nuwen.net/mingw.html). As far as I know, `_BitScanForward64` is an MSVC extension. GCC and Clang have `_builtin_clzll`/`_builtin_ctzll`, although the semantics are slightly different.

3. > One notable distinction from the absl library is that emilib2 utilizes one more byte of each entry(or some entry) to track the distance from the home bucket to the farthest bucket. This design choice enhances its performance on high-frequency insertion and deletion cases.

    Do you mean that for each bucket, you store the distance to the farthest element that hashed to that bucket? It’s not obvious to me how this would help with high-frequency insertion and deletion in particular. But it looks like you use this stored value to terminate unsuccessful lookups early via `if (++offset > get_offset(main_bucket)) break;`, so I’ve noted that in my description of the hash table (see below).

4. At present, the description I have written of emlib2 is:

    _emilib2::HashMap: This table is yet another open-addressing table that uses SIMD instructions to scan multiple hash-code fragments at once for potential key matches. The library is still under development, and details about its implementation are sparse and liable to change. However, one distinguishing quality is that it uses an extra byte per bucket to store the displacement of the farthest key-value pair that hashed to that bucket. This allows early termination of probing during lookups of nonexisting keys._

    _This table's approximate memory overhead is two bytes, plus key-value padding, per bucket, in addition to the size of a key-value pair per vacant bucket._

    _The version benchmarked is [emilib2o.hpp](https://github.com/ktprime/emhash/blob/434a20571a8d6b83b308ee0655a7076b5177e1fc/thirdparty/emilib/emilib2o.hpp) `434a205`, which I modified to set the maximum load factor to 0.875._

    I haven’t written an analysis of emilib2’s performance yet, I intend to say that it shows great promise and could be a good alternative to boost::unordered_dense once it’s stable/ready for public consumption.

5. > My emhash7 can achieve a load factor of 0.999 with minimal performance penalty (300%) compared to other hash maps.

    I would have liked to use a higher maximum load factor (e.g. 0.95) in these benchmarks because my own hash tables cope well in this regard (since they only ever do traditional probing when looking for an empty bucket on insertion). But Abseil and Boost both hard-code 0.875 and have very complex code (as you noted), so I was more or less forced to adopt that load factor.

6. > By the way, I've been testing your code on different hardware and systems, using various compilers and hash functions. For instance, I've tried it on an Apple M2, an AMD 5800H, and an Intel server CPU. The results have been quite different from running it on a standard PC CPU, even though the PC CPU is high-speed, it has less cache memory.

    Interesting! Looks like emilib2o is particularly well suited to the M2.

    Note that the total key count matters quite a lot in these benchmarks. Boost performs particularly well with lower key-counts (the 2,000,000-key benchmarks), which I think means that it benefits from being in the cache more than the other tables. My initial testing shows that emilib2o shows the same benefit as Boost in this regard.

**Comment by ktprime** [comment]
2. thanks for report bugs on ming64

4. in my new design  some continuous entrys share one byte which keep the probe distance not only for find miss, 
`constexpr static uint8_t OFFSET_STEP  = 4`
so it's can save some memory.  if u see the code,   **get_offset(main_bucket)** is also in insert code
, when one entry is erased and then reinsert new data again,  the probe length will kept same as before and reuse the
erased bucket/slot.

5. another difference is I combine 2 probe strategy which may help in some very bad case(clustering very serious)
```
    inline size_t get_next_bucket(size_t next_bucket, size_t offset) const
    {
        next_bucket += offset < 8 ? 16 * offset: _num_buckets / 32; next_bucket += 1;
        return next_bucket & _mask;
    }
  in some of my benchmark case boost and absl are quite slow because of only quadratic probing used.

```
6 if the meta data can fiiled in cpu cache size, then absl/boost will very efficient, but the data set is quite small or very large
(< 2e4 or >  4e^8 items), from my benchmark emhash7 will beats many of the other hash map because of less cache miss.
